import "./globals.css";
import "@repo/ui/styles.css";
import { Quicksand } from "next/font/google"
import Provider from './provider'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Nav } from "@repo/ui/src";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};
const quicksand = Quicksand({
  subsets: ['latin'],
  weight: ['400', '700']
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={quicksand.className} >
        <Provider>
          <Nav />
          <div className="bg-[#EFF5EE] font-bold">
            {children}
          </div>
        </Provider>
      </body>
    </html>
  )
}
