export const dataxVeggies = [
  {
    _id: "9",
    name: "Spring Onions",
    desc: "Go for spring onions with firm, unblemished bulbs and bright green, perky leaves.",
    price: 10.0,
    oldPrice: 0,
    stock: 50,
    sold: 0,
    totalStars: 0,
    type: "vegetable",
    image: "/items/vegetable/spring-onion.jpg",
    dateAdded: new Date("2023-01-01"),
    favouriteUsers: [],
    cartUsers: [],
    comments: [],
  },
  {
    _id: "10",
    name: "Mint",
    desc: "The mint plant is a herbaceous perennial that is widely known.",
    price: 15.0,
    oldPrice: 0,
    stock: 25,
    sold: 25,
    totalStars: 0,
    type: "vegetable",
    image: "/items/vegetable/mint.jpg",
    dateAdded: new Date("2023-01-01"),
    favouriteUsers: [],
    cartUsers: [],
    comments: [],
  },

  {
    _id: "11",
    name: "Basil",
    desc: "To keep basil fresh, trim the stems and place them in a glass or jar of water.",
    price: 8.0,
    oldPrice: 10.0,
    stock: 50,
    sold: 0,
    totalStars: 0,
    type: "vegetable",
    image: "/items/vegetable/basil.jpg",
    dateAdded: new Date("2023-01-01"),
    favouriteUsers: [],
    cartUsers: [],
    comments: [],
  },
  {
    _id: "12",
    name: "Carrots",
    desc: "Carrots can be stored in the refrigerator for up to a month if stored properly.",
    price: 10.0,
    oldPrice: 0,
    stock: 50,
    sold: 0,
    totalStars: 0,
    type: "vegetable",
    image: "/items/vegetable/carrot.jpg",
    dateAdded: new Date("2023-01-01"),
    favouriteUsers: [],
    cartUsers: [],
    comments: [],
  },
  {
    _id: "13",
    name: "Red Radish",
    desc: "The color of a radish is a strong indicator of its taste. Pick the ones that are a rich, full red.",
    price: 20.0,
    oldPrice: 0,
    stock: 50,
    sold: 0,
    totalStars: 0,
    type: "vegetable",
    image: "/items/vegetable/red-radish.jpg",
    dateAdded: new Date("2023-01-01"),
    favouriteUsers: [],
    cartUsers: [],
    comments: [],
  },
  {
    _id: "14",
    name: "Garlic",
    desc: "Garlic (Allium sativum) is a common cooking ingredient that possesses some health benefits.",
    price: 18.0,
    oldPrice: 0,
    stock: 50,
    sold: 0,
    totalStars: 0,
    type: "vegetable",
    image: "/items/vegetable/garlic.jpg",
    dateAdded: new Date("2023-01-01"),
    favouriteUsers: [],
    cartUsers: [],
    comments: [],
  },
  {
    _id: "15",
    name: "Mushroom",
    desc: "They’re fat-free, low-sodium, low-calorie, and cholesterol-free.",
    price: 20.0,
    oldPrice: 0,
    stock: 50,
    sold: 0,
    totalStars: 0,
    type: "vegetable",
    image: "/items/vegetable/mushroom.jpg",
    dateAdded: new Date("2023-01-01"),
    favouriteUsers: [],
    cartUsers: [],
    comments: [],
  },
];

export const datax = [
  {
    _id: "1",
    name: "Avacados",
    desc: "Avocados are a rich source of vitamins C, E, K, and B-6.",
    price: 60.0,
    oldPrice: 0,
    stock: 50,
    sold: 0,
    totalStars: 0,
    type: "fruit",
    image: "/items/fruit/avacado.jpg",
    dateAdded: new Date("2023-01-01"),
    favouriteUsers: [],
    cartUsers: [],
    comments: [],
  },
  {
    _id: "2",
    name: "Kiwi",
    desc: "Kiwi is a small, oval-shaped fruit with a brown fuzzy exterior and vibrant green interior.",
    price: 10.0,
    oldPrice: 15.0,
    stock: 50,
    sold: 0,
    totalStars: 0,
    type: "fruit",
    image: "/items/fruit/kiwi.jpg",
    dateAdded: new Date("2023-01-01"),
    favouriteUsers: [],
    cartUsers: [],
    comments: [],
  },
  {
    _id: "3",
    name: "Fresh Coconut",
    desc: "Coconuts are very nutritious and coconuts are rich in fibre, vitamins.",
    price: 40.0,
    oldPrice: 0,
    stock: 50,
    sold: 0,
    totalStars: 0,
    type: "fruit",
    image: "/items/fruit/coconut.jpg",
    dateAdded: new Date("2023-01-01"),
    favouriteUsers: [],
    cartUsers: [],
    comments: [],
  },
  {
    _id: "4",
    name: "Strawberries",
    desc: "Strawberries are packed with vitamins, fiber and antioxidants.",
    price: 70.0,
    oldPrice: 0,
    stock: 35,
    sold: 4,
    totalStars: 0,
    type: "fruit",
    image: "/items/fruit/strawberry.jpg",
    dateAdded: new Date("2023-01-01"),
    favouriteUsers: [],
    cartUsers: [],
    comments: [],
  },
  {
    _id: "5",
    name: "Blueberries",
    desc: "Carefully hand-picked, these blueberries are crisp and fresh.",
    price: 40.0,
    oldPrice: 0,
    stock: 30,
    sold: 0,
    totalStars: 0,
    type: "fruit",
    image: "/items/fruit/blueberry.jpg",
    dateAdded: new Date("2023-01-01"),
    favouriteUsers: [],
    cartUsers: [],
    comments: [],
  },
  {
    _id: "6",
    name: "Blackberries",
    desc: "Blackberries include a wide range of significant nutrients including potassium.",
    price: 30.0,
    oldPrice: 0,
    stock: 30,
    sold: 0,
    totalStars: 0,
    type: "fruit",
    image: "/items/fruit/blackberry.jpg",
    dateAdded: new Date("2023-01-01"),
    favouriteUsers: [],
    cartUsers: [],
    comments: [],
  },
  {
    _id: "7",
    name: "Green Apples",
    desc: "Green apples delivered fresh! Crisp, fresh and hand-picked! Essential for your kitchen.",
    price: 10.0,
    oldPrice: 0,
    stock: 50,
    sold: 24,
    totalStars: 0,
    type: "fruit",
    image: "/items/fruit/green-apple.jpg",
    dateAdded: new Date("2023-01-01"),
    favouriteUsers: [],
    cartUsers: [],
    comments: [],
  },
  {
    _id: "8",
    name: "Grapes",
    desc: "Grapes are fat free and very low in sodium. Grapes are a very good source of vitamin K.",
    price: 14.0,
    oldPrice: 0,
    stock: 40,
    sold: 0,
    totalStars: 0,
    type: "fruit",
    image: "/items/fruit/grape.jpg",
    dateAdded: new Date("2023-01-01"),
    favouriteUsers: [],
    cartUsers: [],
    comments: [],
  },
];

export const dataInfo = [
  {
    image: "/home/scooter.svg",
    first: "Free Delivery Across the US!",
    second: "Free delivery for all orders above $100",
  },
  {
    image: "/home/heart.svg",
    first: "100% Satisfaction Guarantee!",
    second: "Providing help in case of dissatisfaction",
  },
  {
    image: "/home/chat.svg",
    first: "Top-Notch Support",
    second: "Chat with us if you’ve any questions",
  },
  {
    image: "/home/card.svg",
    first: "Secure Payments",
    second: "We use safest payment technologies",
  },
];

const stripetestingdata = {
  cardno: "4242 4242 4242 4242",
};
