//
// export const fullData = [
//
//   {
//     name: 'Spring Onions',
//     desc: 'Go for spring onions with firm, unblemished bulbs and bright green, perky leaves.',
//     price: 10.00,
//     oldPrice: 0,
//     stock: 50,
//     sold: 0,
//     totalStars: 0,
//     type: 'vegetable',
//     image: '/items/vegetable/spring-onion.jpg',
//     dateAdded: new Date('2023-01-01'),
//     favouriteUsers: [],
//     cartUsers: [],
//     comments: []
//   },
//   {
//     name: 'Mint',
//     desc: 'The mint plant is a herbaceous perennial that is widely known.',
//     price: 15.00,
//     oldPrice: 0,
//     stock: 25,
//     sold: 25,
//     totalStars: 0,
//     type: 'vegetable',
//     image: '/items/vegetable/mint.jpg',
//     dateAdded: new Date('2023-01-01'),
//     favouriteUsers: [],
//     cartUsers: [],
//     comments: []
//   },
//
//   {
//     name: 'Basil',
//     desc: 'To keep basil fresh, trim the stems and place them in a glass or jar of water.',
//     price: 8.00,
//     oldPrice: 10.00,
//     stock: 50,
//     sold: 0,
//     totalStars: 0,
//     type: 'vegetable',
//     image: '/items/vegetable/basil.jpg',
//     dateAdded: new Date('2023-01-01'),
//     favouriteUsers: [],
//     cartUsers: [],
//     comments: []
//   },
//   {
//     name: 'Carrots',
//     desc: 'Carrots can be stored in the refrigerator for up to a month if stored properly.',
//     price: 10.00,
//     oldPrice: 0,
//     stock: 50,
//     sold: 0,
//     totalStars: 0,
//     type: 'vegetable',
//     image: '/items/vegetable/carrot.jpg',
//     dateAdded: new Date('2023-01-01'),
//     favouriteUsers: [],
//     cartUsers: [],
//     comments: []
//   },
//   {
//     name: 'Red Radish',
//     desc: 'The color of a radish is a strong indicator of its taste. Pick the ones that are a rich, full red.',
//     price: 20.00,
//     oldPrice: 0,
//     stock: 50,
//     sold: 0,
//     totalStars: 0,
//     type: 'vegetable',
//     image: '/items/vegetable/red-radish.jpg',
//     dateAdded: new Date('2023-01-01'),
//     favouriteUsers: [],
//     cartUsers: [],
//     comments: []
//   },
//   {
//     name: 'Garlic',
//     desc: 'Garlic (Allium sativum) is a common cooking ingredient that possesses some health benefits.',
//     price: 18.00,
//     oldPrice: 0,
//     stock: 50,
//     sold: 0,
//     totalStars: 0,
//     type: 'vegetable',
//     image: '/items/vegetable/garlic.jpg',
//     dateAdded: new Date('2023-01-01'),
//     favouriteUsers: [],
//     cartUsers: [],
//     comments: []
//   },
//   {
//     name: 'Mushroom',
//     desc: 'They’re fat-free, low-sodium, low-calorie, and cholesterol-free.',
//     price: 20.00,
//     oldPrice: 0,
//     stock: 50,
//     sold: 0,
//     totalStars: 0,
//     type: 'vegetable',
//     image: '/items/vegetable/mushroom.jpg',
//     dateAdded: new Date('2023-01-01'),
//     favouriteUsers: [],
//     cartUsers: [],
//     comments: []
//   },
//
//
//   {
//     name: 'Avacados',
//     desc: 'Avocados are a rich source of vitamins C, E, K, and B-6.',
//     price: 60.00,
//     oldPrice: 0,
//     stock: 50,
//     sold: 0,
//     totalStars: 0,
//     type: 'fruit',
//     image: '/items/fruit/avacado.jpg',
//     dateAdded: new Date('2023-01-01'),
//     favouriteUsers: [],
//     cartUsers: [],
//     comments: []
//   },
//   {
//     name: 'Kiwi',
//     desc: 'Kiwi is a small, oval-shaped fruit with a brown fuzzy exterior and vibrant green interior.',
//     price: 10.00,
//     oldPrice: 15.00,
//     stock: 50,
//     sold: 0,
//     totalStars: 0,
//     type: 'fruit',
//     image: '/items/fruit/kiwi.jpg',
//     dateAdded: new Date('2023-01-01'),
//     favouriteUsers: [],
//     cartUsers: [],
//     comments: []
//   },
//   {
//     name: 'Fresh Coconut',
//     desc: 'Coconuts are very nutritious and coconuts are rich in fibre, vitamins.',
//     price: 40.00,
//     oldPrice: 0,
//     stock: 50,
//     sold: 0,
//     totalStars: 0,
//     type: 'fruit',
//     image: '/items/fruit/coconut.jpg',
//     dateAdded: new Date('2023-01-01'),
//     favouriteUsers: [],
//     cartUsers: [],
//     comments: []
//   },
//   {
//     name: 'Strawberries',
//     desc: 'Strawberries are packed with vitamins, fiber and antioxidants.',
//     price: 70.00,
//     oldPrice: 0,
//     stock: 35,
//     sold: 4,
//     totalStars: 0,
//     type: 'fruit',
//     image: '/items/fruit/strawberry.jpg',
//     dateAdded: new Date('2023-01-01'),
//     favouriteUsers: [],
//     cartUsers: [],
//     comments: []
//   },
//   {
//     name: 'Blueberries',
//     desc: 'Carefully hand-picked, these blueberries are crisp and fresh.',
//     price: 40.00,
//     oldPrice: 0,
//     stock: 30,
//     sold: 0,
//     totalStars: 0,
//     type: 'fruit',
//     image: '/items/fruit/blueberry.jpg',
//     dateAdded: new Date('2023-01-01'),
//     favouriteUsers: [],
//     cartUsers: [],
//     comments: []
//   },
//   {
//     name: 'Blackberries',
//     desc: 'Blackberries include a wide range of significant nutrients including potassium.',
//     price: 30.00,
//     oldPrice: 0,
//     stock: 30,
//     sold: 0,
//     totalStars: 0,
//     type: 'fruit',
//     image: '/items/fruit/blackberry.jpg',
//     dateAdded: new Date('2023-01-01'),
//     favouriteUsers: [],
//     cartUsers: [],
//     comments: []
//   },
//   {
//     name: 'Green Apples',
//     desc: 'Green apples delivered fresh! Crisp, fresh and hand-picked! Essential for your kitchen.',
//     price: 10.00,
//     oldPrice: 0,
//     stock: 50,
//     sold: 24,
//     totalStars: 0,
//     type: 'fruit',
//     image: '/items/fruit/green-apple.jpg',
//     dateAdded: new Date('2023-01-01'),
//     favouriteUsers: [],
//     cartUsers: [],
//     comments: []
//   },
//   {
//     name: 'Grapes',
//     desc: 'Grapes are fat free and very low in sodium. Grapes are a very good source of vitamin K.',
//     price: 14.00,
//     oldPrice: 0,
//     stock: 40,
//     sold: 0,
//     totalStars: 0,
//     type: 'fruit',
//     image: '/items/fruit/grape.jpg',
//     dateAdded: new Date('2023-01-01'),
//     favouriteUsers: [],
//     cartUsers: [],
//     comments: []
//   },
//
//
//   {
//     name: 'Chuck Steak',
//     desc: 'Wrap the meat in freezer paper, freezer bags or aluminum foil.',
//     price: 350.00,
//     oldPrice: 0,
//     stock: 10,
//     sold: 0,
//     totalStars: 0,
//     type: 'meat',
//     image: '/items/meat/chuck-steak.jpg',
//     dateAdded: new Date('2023-01-01'),
//     favouriteUsers: [],
//     cartUsers: [],
//     comments: []
//   },
//   {
//     name: 'Spiced Beef Pastrami',
//     desc: 'Made with hand-trimmed beef and seasoned to perfection.',
//     price: 99.00,
//     oldPrice: 0,
//     stock: 10,
//     sold: 0,
//     totalStars: 0,
//     type: 'meat',
//     image: '/items/meat/beef-pastrami.jpg',
//     dateAdded: new Date('2023-01-01'),
//     favouriteUsers: [],
//     cartUsers: [],
//     comments: []
//   },
//   {
//     name: 'Efepasa Sausage',
//     desc: 'Enjoy the traditional flavour of Efepasa 100% beef finger sucuk.',
//     price: 140.00,
//     oldPrice: 0,
//     stock: 10,
//     sold: 0,
//     totalStars: 0,
//     type: 'meat',
//     image: '/items/meat/sausage.jpg',
//     dateAdded: new Date('2023-01-01'),
//     favouriteUsers: [],
//     cartUsers: [],
//     comments: []
//   },
//   {
//     name: 'Whole Duck',
//     desc: 'The whole halal duck is around ~1.6 kilograms.',
//     price: 250.00,
//     oldPrice: 0,
//     stock: 10,
//     sold: 0,
//     totalStars: 0,
//     type: 'meat',
//     image: '/items/meat/whole-duck.jpg',
//     dateAdded: new Date('2023-01-01'),
//     favouriteUsers: [],
//     cartUsers: [],
//     comments: []
//   },
//   {
//     name: 'Chicken Breast Mince',
//     desc: 'Being ideal for meatballs and burgers, this Chicken Breast Mince is tasty and fresh.',
//     price: 75.00,
//     oldPrice: 0,
//     stock: 10,
//     sold: 0,
//     totalStars: 0,
//     type: 'meat',
//     image: '/items/meat/chicken-mince.jpg',
//     dateAdded: new Date('2023-01-01'),
//     favouriteUsers: [],
//     cartUsers: [],
//     comments: []
//   },
//   {
//     name: 'Whole British Goose',
//     desc: 'In addition to its delicious taste, British Goose with Giblets is also a healthy option.',
//     price: 140.00,
//     oldPrice: 0,
//     stock: 10,
//     sold: 0,
//     totalStars: 0,
//     type: 'meat',
//     image: '/items/meat/british-goose.jpg',
//     dateAdded: new Date('2023-01-01'),
//     favouriteUsers: [],
//     cartUsers: [],
//     comments: []
//   },
//
//
//
//   {
//     name: 'Black Catfish',
//     desc: 'Like most of the bullheads (and even flathead catfish), it has a squared tail fin.',
//     price: 120.00,
//     oldPrice: 0,
//     stock: 10,
//     sold: 0,
//     totalStars: 0,
//     type: 'seafood',
//     image: '/items/seafood/black-catfish.jpg',
//     dateAdded: new Date('2023-01-01'),
//     favouriteUsers: [],
//     cartUsers: [],
//     comments: []
//   },
//   {
//     name: 'Oak Smoked Salmon',
//     desc: 'Our delicious oak smoked Salmon is an excellent source of protein.',
//     price: 40.00,
//     oldPrice: 65.00,
//     stock: 15,
//     sold: 9,
//     totalStars: 0,
//     type: 'seafood',
//     image: '/items/seafood/salmon.jpg',
//     dateAdded: new Date('2023-01-01'),
//     favouriteUsers: [],
//     cartUsers: [],
//     comments: []
//   },
//   {
//     name: 'Fresh Crucian Carp',
//     desc: 'Crucian Carp is a freshwater fish that is known for its firm, white flesh and mild, sweet flavor.',
//     price: 175.00,
//     oldPrice: 0,
//     stock: 15,
//     sold: 0,
//     totalStars: 0,
//     type: 'seafood',
//     image: '/items/seafood/crucian-carp.jpg',
//     dateAdded: new Date('2023-01-01'),
//     favouriteUsers: [],
//     cartUsers: [],
//     comments: []
//   },
//   {
//     name: 'Jumbo Prawns',
//     desc: 'King Prawns are almost pure protein with little fat. 100 grams of cooked King Prawns is approximately 70 calories with 15 grams of protein.',
//     price: 450.00,
//     oldPrice: 0,
//     stock: 15,
//     sold: 0,
//     totalStars: 0,
//     type: 'seafood',
//     image: '/items/seafood/prawn.jpg',
//     dateAdded: new Date('2023-01-01'),
//     favouriteUsers: [],
//     cartUsers: [],
//     comments: []
//   },
//   {
//     name: 'King Prawns',
//     desc: 'Great for a healthy salad and sandwiches, mix with our crayfish tails to make an even better sandwich.',
//     price: 30.00,
//     oldPrice: 40.00,
//     stock: 20,
//     sold: 8,
//     totalStars: 0,
//     type: 'seafood',
//     image: '/items/seafood/king-prawn.jpg',
//     dateAdded: new Date('2023-01-01'),
//     favouriteUsers: [],
//     cartUsers: [],
//     comments: []
//   },
//   {
//     name: 'Fresh Scottish Lobster',
//     desc: 'One of our high-end products, Scottish Lobster, are caught from the East Coast of Scotland.',
//     price: 250.00,
//     oldPrice: 0,
//     stock: 20,
//     sold: 0,
//     totalStars: 0,
//     type: 'seafood',
//     image: '/items/seafood/scottish-lobster.jpg',
//     dateAdded: new Date('2023-01-01'),
//     favouriteUsers: [],
//     cartUsers: [],
//     comments: []
//   },
//   {
//     name: 'Fresh Lobster',
//     desc: '100 grams of cooked lobster is approximately 90 calories with 19 grams of protein.',
//     price: 120.00,
//     oldPrice: 150.00,
//     stock: 30,
//     sold: 11,
//     totalStars: 0,
//     type: 'seafood',
//     image: '/items/seafood/lobster.jpg',
//     dateAdded: new Date('2023-01-01'),
//     favouriteUsers: [],
//     cartUsers: [],
//     comments: []
//   },
//
//
//
//
//   {
//     name: 'Ciabatta Bake',
//     desc: 'Ciabatta is a white bread that stems from a baker in Rovigo, Veneto, Italy.',
//     price: 8.00,
//     oldPrice: 9.00,
//     stock: 10,
//     sold: 9,
//     totalStars: 0,
//     type: 'baking',
//     image: '/items/baking/ciabatta-bake.jpg',
//     dateAdded: new Date('2023-01-01'),
//     favouriteUsers: [],
//     cartUsers: [],
//     comments: []
//   },
//   {
//     name: 'Menissez Mini Pains Bake',
//     desc: 'The 300g part-baked white rolls are packed by 6 and weigh approximately 50g each.',
//     price: 15.00,
//     oldPrice: 0,
//     stock: 20,
//     sold: 0,
//     totalStars: 0,
//     type: 'baking',
//     image: '/items/baking/mini-pain.jpg',
//     dateAdded: new Date('2023-01-01'),
//     favouriteUsers: [],
//     cartUsers: [],
//     comments: []
//   },
//   {
//     name: 'Tortilla',
//     desc: 'Tortillas are a unique, chemically leavened product.',
//     price: 8.00,
//     oldPrice: 0,
//     stock: 20,
//     sold: 0,
//     totalStars: 0,
//     type: 'baking',
//     image: '/items/baking/tortilla.jpg',
//     dateAdded: new Date('2023-01-01'),
//     favouriteUsers: [],
//     cartUsers: [],
//     comments: []
//   },
//   {
//     name: 'Triangle Filo Pastry',
//     desc: 'Yufka is a thin, round, unleavened flatbread from Turkey, similar to lavash.',
//     price: 10.00,
//     oldPrice: 0,
//     stock: 20,
//     sold: 0,
//     totalStars: 0,
//     type: 'baking',
//     image: '/items/baking/filo-pastry.jpg',
//     dateAdded: new Date('2023-01-01'),
//     favouriteUsers: [],
//     cartUsers: [],
//     comments: []
//   },
//   {
//     name: 'Cow Cheese',
//     desc: 'Comté is a traditional, hard cheese with similar characteristics to the Swiss gruyere.',
//     price: 17.00,
//     oldPrice: 0,
//     stock: 25,
//     sold: 0,
//     totalStars: 0,
//     type: 'baking',
//     image: '/items/baking/cow-cheese.jpg',
//     dateAdded: new Date('2023-01-01'),
//     favouriteUsers: [],
//     cartUsers: [],
//     comments: []
//   },
//   {
//     name: 'Sheep Cheese',
//     desc: 'This cheese is supple, creamy and buttery with a nutty tang when young and becomes more firm as the cheese ripens.',
//     price: 15.00,
//     oldPrice: 0,
//     stock: 25,
//     sold: 0,
//     totalStars: 0,
//     type: 'baking',
//     image: '/items/baking/sheep-cheese.jpg',
//     dateAdded: new Date('2023-01-01'),
//     favouriteUsers: [],
//     cartUsers: [],
//     comments: []
//   },
//   {
//     name: 'Organic Free-Range Eggs 6 Pack',
//     desc: 'Fresh eggs from organic free range hens roaming outdoors.',
//     price: 25.00,
//     oldPrice: 0,
//     stock: 25,
//     sold: 0,
//     totalStars: 0,
//     type: 'baking',
//     image: '/items/baking/sheep-cheese.jpg',
//     dateAdded: new Date('2023-01-01'),
//     favouriteUsers: [],
//     cartUsers: [],
//     comments: []
//   },
//
//
//
//
//   {
//     name: 'Apple Juice',
//     desc: '100% Apple Juice is a premium quality beverage made from the freshest and most delicious organic apples.',
//     price: 15.00,
//     oldPrice: 19.00,
//     stock: 5,
//     sold: 0,
//     totalStars: 0,
//     type: 'drink',
//     image: '/items/drink/apple-juice.jpg',
//     dateAdded: new Date('2023-01-01'),
//     favouriteUsers: [],
//     cartUsers: [],
//     comments: []
//   },
//   {
//     name: 'Still Water',
//     desc: 'It’s a uniquely sourced spring water that’s always refreshing and naturally hydrating.',
//     price: 20.00,
//     oldPrice: 0,
//     stock: 5,
//     sold: 0,
//     totalStars: 0,
//     type: 'drink',
//     image: '/items/drink/water.jpg',
//     dateAdded: new Date('2023-01-01'),
//     favouriteUsers: [],
//     cartUsers: [],
//     comments: []
//   },
//   {
//     name: 'Organic Carrot Juice',
//     desc: 'Organic Carrot Juice is carrot juice at its best using only the best organic carrots.',
//     price: 35.00,
//     oldPrice: 0,
//     stock: 5,
//     sold: 0,
//     totalStars: 0,
//     type: 'drink',
//     image: '/items/drink/carrot-juice.jpg',
//     dateAdded: new Date('2023-01-01'),
//     favouriteUsers: [],
//     cartUsers: [],
//     comments: []
//   },
//   {
//     name: 'Natural Coconut Water',
//     desc: 'Never from Concentrate | 100% recyclable packaging | Low calorie and no fat, we’ll drink to that!',
//     price: 10.00,
//     oldPrice: 0,
//     stock: 7,
//     sold: 0,
//     totalStars: 0,
//     type: 'drink',
//     image: '/items/drink/coconut-water.jpg',
//     dateAdded: new Date('2023-01-01'),
//     favouriteUsers: [],
//     cartUsers: [],
//     comments: []
//   },
//   {
//     name: 'Milk',
//     desc: 'Store in a cool, dry place. Best consumed within 3 days of opening, but may still be great after this date too.',
//     price: 10.00,
//     oldPrice: 0,
//     stock: 9,
//     sold: 0,
//     totalStars: 0,
//     type: 'drink',
//     image: '/items/drink/milk.jpg',
//     dateAdded: new Date('2023-01-01'),
//     favouriteUsers: [],
//     cartUsers: [],
//     comments: []
//   },
// ]
